name = "AeroXCobblemon"
author = "Alex"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "352f1c8f8555298dc8f80267f9578435a00838dfb83dcf2213f4946dcbd18254"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"

[options]
datapack-folder = "./datapacks"
