name = "AeroXCobblemon"
author = "Alex"
version = "2.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0cc0f36c5caa7f0ca6f62c942a0917396730313835b386559b4e96bcfbd5adee"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"

[options]
datapack-folder = "./datapacks"
