name = "AeroXCobblemon"
author = "Alex"
version = "2.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b0e49fb9f9df6b2546896e18135a4a34999a10764d15490dfba87bff1330de4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"

[options]
datapack-folder = "./datapacks"
