name = "AeroXCobblemon"
author = "Alex"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce8d5f2aef80eb0c195ec7f35f5a9101bb0f163ff61506997b65c847a951c2ed"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"

[options]
datapack-folder = "./datapacks"