name = "AeroXCobblemon"
author = "Alex"
version = "2.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "30cdb012bf354896e339f3081477dbb36efd6109213b77f582589663eb2161eb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"

[options]
datapack-folder = "./datapacks"
